#!/usr/bin/env node
// README.md의 <!-- STATS:START -->..<!-- STATS:END --> 블록을 현재 데이터로 갱신한다.
// 주간 운영 리뷰(및 원하면 일일 루틴)가 실행 → 개발 현황이 README에 자동 반영.
//
//   node tools/update-readme.js                 # 갱신(오늘 날짜 or stats.updatedAt)
//   node tools/update-readme.js --date=2026-08-03
//   node tools/update-readme.js --check         # 변경 없이 결과만 출력(비교용)
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const read = (p, f) => { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return f; } };
const idols = read(path.join(ROOT, 'tools', 'idols.json'), []);
const stats = read(path.join(ROOT, 'tools', 'stats.json'), {});
const CAT_MIN = 30;

const groups = new Set(idols.map(x => x.group));
const byCat = {};
idols.forEach(x => { const c = x.cat || 'K-idol'; byCat[c] = (byCat[c] || 0) + 1; });
// index.html의 CAT_NAMES[*].ko와 같은 라벨을 쓴다(카테고리 신설 시 양쪽 모두 추가).
const CAT_KO = { 'K-idol':'한국 아이돌', 'K-actor':'한국 배우', 'J-idol':'일본 아이돌', 'C-actor':'중국 배우', 'US-actor':'미국 배우', 'Etc':'기타' };
const visible = Object.entries(byCat).filter(([, n]) => n >= CAT_MIN).sort((a, b) => b[1] - a[1])
  .map(([c, n]) => `${CAT_KO[c] || c}(${n})`).join(' · ') || '한국 아이돌';

const argDate = (process.argv.find(a => a.startsWith('--date=')) || '').slice(7);
const date = argDate || stats.updatedAt || new Date().toISOString().slice(0, 10);

const block = `<!-- STATS:START (auto-generated by tools/update-readme.js — do not edit by hand) -->
- **수록 현황(자동 갱신)**: **${idols.length}명 · ${groups.size}그룹** · 노출 카테고리: ${visible} · ${date} 기준
<!-- STATS:END -->`;

const rp = path.join(ROOT, 'README.md');
const md = fs.readFileSync(rp, 'utf8');
const re = /<!-- STATS:START[\s\S]*?<!-- STATS:END -->/;
if (!re.test(md)) { console.error('README.md에 STATS 마커가 없습니다.'); process.exit(1); }

const next = md.replace(re, block);
if (process.argv.includes('--check')) {
  console.log(block);
  console.log(next === md ? '\n(변경 없음)' : '\n(변경 예정)');
} else {
  if (next !== md) { fs.writeFileSync(rp, next); console.log(`README 현황 갱신: ${idols.length}명 / ${groups.size}그룹 (${date})`); }
  else { console.log('README 현황 변경 없음.'); }
}
